services:

  # ======================
  # MYSQL MASTER
  # ======================
  mysql_master:
    image: mysql:8.0
    container_name: mysql_master
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: voting_db
      MYSQL_USER: voteuser
      MYSQL_PASSWORD: votepassword
    ports:
      - "3306:3306"
    volumes:
      - master_data:/var/lib/mysql
      - ./master_conf:/etc/mysql/conf.d

  # ======================
  # MYSQL SLAVE 1
  # ======================
  mysql_slave1:
    image: mysql:8.0
    container_name: mysql_slave1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: voting_db
      MYSQL_USER: voteuser
      MYSQL_PASSWORD: votepassword
    ports:
      - "3307:3306"
    volumes:
      - slave1_data:/var/lib/mysql
      - ./slave1_conf:/etc/mysql/conf.d
    depends_on:
      - mysql_master

  # ======================
  # MYSQL SLAVE 2
  # ======================
  mysql_slave2:
    image: mysql:8.0
    container_name: mysql_slave2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: voting_db
      MYSQL_USER: voteuser
      MYSQL_PASSWORD: votepassword
    ports:
      - "3308:3306"
    volumes:
      - slave2_data:/var/lib/mysql
      - ./slave2_conf:/etc/mysql/conf.d
    depends_on:
      - mysql_master

  # ======================
  # BACKEND 1
  # ======================
  backend1:
    build: ./backend
    container_name: backend1
    restart: always
    environment:
      DB_HOST_MASTER: mysql_master
      DB_HOST_SLAVE1: mysql_slave1
      DB_HOST_SLAVE2: mysql_slave2
      DB_USER: voteuser
      DB_PASSWORD: votepassword
      DB_NAME: voting_db
      BACKEND_NAME: backend1

  # ======================
  # BACKEND 2
  # ======================
  backend2:
    build: ./backend
    container_name: backend2
    restart: always
    environment:
      DB_HOST_MASTER: mysql_master
      DB_HOST_SLAVE1: mysql_slave1
      DB_HOST_SLAVE2: mysql_slave2
      DB_USER: voteuser
      DB_PASSWORD: votepassword
      DB_NAME: voting_db
      BACKEND_NAME: backend2

  # ======================
  # BACKEND 3
  # ======================
  backend3:
    build: ./backend
    container_name: backend3
    restart: always
    environment:
      DB_HOST_MASTER: mysql_master
      DB_HOST_SLAVE1: mysql_slave1
      DB_HOST_SLAVE2: mysql_slave2
      DB_USER: voteuser
      DB_PASSWORD: votepassword
      DB_NAME: voting_db
      BACKEND_NAME: backend3

  # ======================
  # NGINX LOAD BALANCER
  # ======================
  nginx:
    image: nginx:latest
    container_name: nginx_lb
    restart: always
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1
      - backend2
      - backend3

  # ======================
  # FRONTEND
  # ======================
  frontend:
    build: ./frontend
    container_name: voting-frontend-dev
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ng serve --host 0.0.0.0 --port 4200 --poll 2000
    depends_on:
      - nginx

# ======================
# VOLUMES
# ======================
volumes:
  master_data:
  slave1_data:
  slave2_data: